site_name: connekt
repo_name: c-fraser/connekt
repo_url: https://github.com/c-fraser/connekt
site_description: 'Graph data structure for Kotlin'
site_author: c-fraser
copyright: 'Copyright &copy; 2022 c-fraser'
nav:
  - connekt: index.md
theme:
  name: 'material'
  favicon: favicon.ico
  logo: connekt.png
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: default
    primary: 'blue grey'
    accent: teal
  features:
    - toc.integrate
    - content.code.copy
    - content.code.select
    - navigation.tabs.sticky
extra_css:
  - extra.css
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
