[versions]
kotlin = "2.2.21"
kotest = "6.0.7"
knit = "0.5.0"
ktfmt = "0.58"

[libraries]
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-framework-engine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
knit = { module = "org.jetbrains.kotlinx:kotlinx-knit", version.ref = "knit" }
knit-test = { module = "org.jetbrains.kotlinx:kotlinx-knit-test", version.ref = "knit" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
spotless = { id = "com.diffplug.spotless", version = "8.0.0" }
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.23.8" }
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0" }
jreleaser = { id = "org.jreleaser", version = "1.21.0" }
dependency-versions = { id = "com.github.ben-manes.versions", version = "0.53.0" }
kover = { id = "org.jetbrains.kotlinx.kover", version = "0.9.3" }
compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version = "0.18.1" }
