name: Release
on:
  workflow_dispatch:
jobs:
  test:
    name: test
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            test-task: macosX64Test
          - os: windows-latest
            test-task: mingwX64Test
          - os: ubuntu-latest
            test-task: check
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Execute test
        run: ./gradlew ${{matrix.test-task}} --stacktrace
  release:
    needs: test
    name: release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Execute release
        run: ./gradlew jreleaserFullRelease publishToSonatype closeAndReleaseSonatypeStagingRepository
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          GPG_SIGNING_KEY: ${{secrets.GPG_SIGNING_KEY}}
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}